---
default:
  labels:
    - color: 0ffa16
      description: Indicates a PR has been approved by an approver from all required OWNERS files.
      name: approved
      target: prs
      prowPlugin: approve
      addedBy: approvers
    - color: e11d21
      description: Indicates that a PR should not merge because it is a work in progress.
      name: do-not-merge/work-in-progress
      target: prs
      prowPlugin: wip
      addedBy: prow
    - color: 7057ff
      description: Denotes an issue ready for a new contributor, according to the "help wanted" guidelines.
      name: 'good first issue'
      target: issues
      prowPlugin: help
      addedBy: anyone
    - color: 006b75
      description: Denotes an issue that needs help from a contributor. Must meet "help wanted" guidelines.
      name: 'help wanted'
      target: issues
      prowPlugin: help
      addedBy: anyone
    - color: e11d21
      description: Categorizes issue or PR as related to adding, removing, or otherwise changing an API
      name: kind/api-change
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: e11d21
      description: Categorizes issue or PR as related to a bug.
      name: kind/bug
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to cleaning up code, process, or technical debt.
      name: kind/cleanup
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to design.
      name: kind/design
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to documentation.
      name: kind/documentation
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: e11d21
      description: Categorizes issue or PR as related to a consistently or frequently failing test.
      name: kind/failing-test
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to a new feature.
      name: kind/feature
      previously:
        - name: enhancement
        - name: kind/enhancement
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: f7c6c7
      description: Categorizes issue or PR as related to a flaky test.
      name: kind/flake
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: bfdadc
      description: Categorizes issue as related to a proposal.
      name: kind/proposal
      target: issues
      prowPlugin: label
      addedBy: anyone
    - color: bfeadc
      description: Categorizes issue as related to a support request.
      name: kind/support
      target: issues
      prowPlugin: label
      addedBy: anyone
    - color: 15dd18
      description: Indicates that a PR is ready to be merged.
      name: lgtm
      target: prs
      prowPlugin: lgtm
      addedBy: reviewers or members
    - color: ee9900
      description: Denotes a PR that changes 100-499 lines, ignoring generated files.
      name: size/L
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: eebb00
      description: Denotes a PR that changes 30-99 lines, ignoring generated files.
      name: size/M
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: 77bb00
      description: Denotes a PR that changes 10-29 lines, ignoring generated files.
      name: size/S
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: ee5500
      description: Denotes a PR that changes 500-999 lines, ignoring generated files.
      name: size/XL
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: "009900"
      description: Denotes a PR that changes 0-9 lines, ignoring generated files.
      name: size/XS
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: ee0000
      description: Denotes a PR that changes 1000+ lines, ignoring generated files.
      name: size/XXL
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: ffaa00
      description: Denotes a PR that should be squashed by tide when it merges.
      name: tide/merge-method-squash
      target: prs
      addedBy: humans
    - color: ffaa00
      description: Denotes a PR that should be rebased by tide when it merges.
      name: tide/merge-method-rebase
      target: prs
      addedBy: humans
    - color: ffaa00
      description: Denotes a PR that should use a standard merge by tide when it merges.
      name: tide/merge-method-merge
      target: prs
      addedBy: humans
    - color: e11d21
      description: Denotes an issue that blocks the tide merge queue for a branch while it is open.
      name: tide/merge-blocker
      target: issues
      addedBy: humans
    - color: 0052cc
      description: Categorizes issue or PR as related to deploy.
      name: area/deploy
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: 0052cc
      description: Categorizes issue or PR as related to testing.
      name: area/testing
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: fb8532
      description: Indicates an issue is a duplicate of other open issue.
      name: triage/duplicate
      target: issues
      prowPlugin: label
      addedBy: anyone
    - color: d15704
      description: Indicates an issue needs more information in order to work on it.
      name: triage/needs-information
      target: issues
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG API Machinery.
      name: sig/api-machinery
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Apps.
      name: sig/apps
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Architecture.
      name: sig/architecture
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Auth.
      name: sig/auth
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Docs.
      name: sig/docs
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Multicluster.
      name: sig/multicluster
      previously:
        - name: sig/federation
        - name: 'sig/federation (deprecated - do not use)'
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Network.
      name: sig/network
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Release.
      name: sig/release
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Scalability.
      name: sig/scalability
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Security.
      name: sig/security
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Storage.
      name: sig/storage
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG Testing.
      name: sig/testing
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: d2b48c
      description: Categorizes an issue or PR as relevant to SIG UI.
      name: sig/ui
      target: both
      prowPlugin: label
      addedBy: anyone

repos:
  kubesphere/kubesphere:
    labels:
      - color: 0052cc
        description: Application management, code in apps/
        name: area/apps
        target: both
        prowPlugin: label
        addedBy: anyone
        previously:
          - name: area/cluster-infra
      - color: 0052cc
        description: Categorizes an issue or PR as relevant to console.
        name: area/console
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Bash scripts, testing them, writing less of them, code in infra/gcp/
        name: area/bash
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Issues or PRs related to billing
        name: area/billing
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Issues or PRs related to multi-cluster.
        name: area/multicluster
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Issues or PRs related to alerting.
        name: area/logging
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Code in k8s.gcr.io/
        name: area/k8s.gcr.io
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Google Groups management, code in groups/
        name: area/groups
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Infrastructure management, infrastructure design, code in infra/
        name: area/infra
        target: both
        prowPlugin: label
        addedBy: anyone
        previously:
          - name: area/cluster-infra
      - color: 0052cc
        description: Issues or PRs related to monitoring of the Kubernetes project infrastructure
        name: area/infra/monitoring
        target: both
        prowPlugin: label
        addedBy: anyone
        deleteAfter: "2021-08-04T00:00:00Z"
      - color: 0052cc
        description: Issues or PR related to reliability of the Kubernetes project infrastructure
        name: area/infra/reliability
        target: both
        prowPlugin: label
        addedBy: anyone
        deleteAfter: "2021-08-04T00:00:00Z"
      - color: 0052cc
        description: Crafting policy, policy decisions, code in policy/
        name: area/policy
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Setting up or working with prow in general, prow.k8s.io, prow build clusters
        name: area/prow
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Issues or PRs related to the Release Engineering subproject
        name: area/release-eng
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: 0052cc
        description: Indicates an issue on api area.
        name: area/api
        target: issues
        addedBy: label
      - color: 0052cc
        description: Issues or PRs related to refactoring the kubernetes e2e test framework
        name: area/e2e-test-framework
        target: both
        addedBy: label
      - color: 0052cc
        description: Issues or PRs related to the Release subproject
        name: area/release
        target: both
        addedBy: label
      - color: e11d21
        description: Indicates a PR lacks a `kind/foo` label and requires one.
        name: do-not-merge/needs-kind
        target: prs
        prowPlugin: require-matching-label
        addedBy: prow
      - color: e11d21
        description: Indicates an issue or PR lacks a `sig/foo` label and requires one.
        name: do-not-merge/needs-sig
        target: prs
        prowPlugin: require-matching-label
        addedBy: prow
      - color: 0052cc
        description: Audit of project resources, audit followup issues, code in audit/
        name: area/auditing
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: e11d21
        description: Indicates that the UI text needs to be reviewed by the technical writing team.
        name: kind/require-ui-text-review
        target: both
        prowPlugin: label
        addedBy: anyone
  kubesphere/console:
    labels:
      - color: e11d21
        description: Indicates that the UI text needs to be reviewed by the technical writing team.
        name: kind/require-ui-text-review
        target: both
        prowPlugin: label
        addedBy: anyone
  kubesphere/qkcp:
    labels:     
      - color: FF9912
        description: 
        name: priority/Medium
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: E3CF57
        description: 
        name: priority/Low
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: ee5500
        description: 
        name: priority/High
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: c7def8
        description: Categorizes issue or PR as related to documentation.
        name: kind/documentation
        target: both
        prowPlugin: label
        addedBy: anyone
      - color: c7def8
        description: Categorizes issue or PR as related to a new feature.
        name: kind/feature
        target: both
        prowPlugin: label
        addedBy: anyone
